Repository fabricadesoftwareufs/AutomacaoSalasWeb, pull requests merged in 2023-02, with the labels that each got.

#126 fix: inicializar dados no input data de nascimento em editar usuário
  Codigo/ModuloDeSoftware/WebAPI/SalasUfsWeb/Views/Usuario/Edit.cshtml
Labels: correcao

#128 Analisar se os dados dos usuarios estão sendo alterados
  Codigo/ModuloDeSoftware/WebAPI/Business/UsuarioService.cs
  Codigo/ModuloDeSoftware/WebAPI/Models/UsuarioModel.cs
  Codigo/ModuloDeSoftware/WebAPI/SalasUfsWeb/Controllers/UsuarioController.cs
  Codigo/ModuloDeSoftware/WebAPI/SalasUfsWeb/Views/Usuario/Create.cshtml
  Codigo/ModuloDeSoftware/WebAPI/SalasUfsWeb/Views/Usuario/Edit.cshtml
Labels: bug

#133 Analisar se está listando todos os usuário com exceção quem está logado
  Codigo/ModuloDeSoftware/WebAPI/Business/Interface/IUsuarioService.cs
  Codigo/ModuloDeSoftware/WebAPI/Business/UsuarioService.cs
  Codigo/ModuloDeSoftware/WebAPI/SalasUfsWeb/Controllers/BlocoController.cs
  Codigo/ModuloDeSoftware/WebAPI/SalasUfsWeb/Controllers/EquipamentoController.cs
  Codigo/ModuloDeSoftware/WebAPI/SalasUfsWeb/Controllers/HardwareDeSalaController.cs
  Codigo/ModuloDeSoftware/WebAPI/SalasUfsWeb/Controllers/HomeController.cs
  Codigo/ModuloDeSoftware/WebAPI/SalasUfsWeb/Controllers/MetodosAuxiliaresController.cs
  Codigo/ModuloDeSoftware/WebAPI/SalasUfsWeb/Controllers/PlanejamentoController.cs
  Codigo/ModuloDeSoftware/WebAPI/SalasUfsWeb/Controllers/ReservaSalaController.cs
  Codigo/ModuloDeSoftware/WebAPI/SalasUfsWeb/Controllers/SalaController.cs
  Codigo/ModuloDeSoftware/WebAPI/SalasUfsWeb/Controllers/SalaParticularController.cs
  Codigo/ModuloDeSoftware/WebAPI/SalasUfsWeb/Controllers/UsuarioController.cs
  Codigo/ModuloDeSoftware/WebAPI/SalasUfsWeb/appsettings.json
Labels: correcao

#135 Feat: Adiciona deploy automático
  .github/workflows/main-sistema-web.yml
  .github/workflows/main-web-api.yml
  .github/workflows/main.yml
Labels: enhancement

#137 Ajusta chamada de metodo
  Codigo/ModuloDeSoftware/WebAPI/SalasUfsWeb/Controllers/UsuarioController.cs
Labels: correcao

#138 feat: deploy automático
  .github/workflows/main-sistema-web.yml
  .github/workflows/main-web-api.yml
Labels: enhancement
