Repository fabricadesoftwareufs/AutomacaoSalasWeb, pull requests merged in 2025-02, with the labels that each got.

#268 Ajustar Métodos da Api que não estão funcionado.
  AnaliseProjeto/Database/dump_dados.sql
  Codigo/ModuloDeSoftware/AutomacaoSalas/SalasAPI/Controllers/AuthController.cs
  Codigo/ModuloDeSoftware/AutomacaoSalas/SalasAPI/Controllers/TipoUsuarioController.cs
Labels: documentation, correcao

#274 Ajustar a associação de equipamento com sala
  Codigo/ModuloDeSoftware/AutomacaoSalas/Business/HardwareDeSalaService.cs
  Codigo/ModuloDeSoftware/AutomacaoSalas/Business/Interface/IHardwareDeSalaService.cs
  Codigo/ModuloDeSoftware/AutomacaoSalas/SalasWeb/Controllers/EquipamentoController.cs
  Codigo/ModuloDeSoftware/AutomacaoSalas/SalasWeb/Views/Equipamento/Create.cshtml
Labels: correcao

#276 Ajustar a View Model Index de ConexaoInternet
  Codigo/ModuloDeSoftware/AutomacaoSalas/SalasWeb/Views/ConexaoInternet/Index.cshtml
  Codigo/ModuloDeSoftware/AutomacaoSalas/SalasWeb/Views/Shared/_MenuPartial.cshtml
Labels: correcao

#292 Procurar na API rest um método que devolve os sensores e atuadores
  Codigo/ModuloDeSoftware/AutomacaoSalas/Business/CodigoInfravermelhoService.cs
  Codigo/ModuloDeSoftware/AutomacaoSalas/Business/HardwareDeSalaService.cs
  Codigo/ModuloDeSoftware/AutomacaoSalas/Business/Interface/ICodigoInfravermelhoService.cs
  Codigo/ModuloDeSoftware/AutomacaoSalas/SalasAPI/Controllers/InfravermelhoController.cs
Labels: enhancement, correcao

#293 Adicionar no detalis os pontos de acesso adicionados
  AnaliseProjeto/Database/dump_dados.sql
  Codigo/ModuloDeSoftware/AutomacaoSalas/Business/ConexaoInternetService.cs
  Codigo/ModuloDeSoftware/AutomacaoSalas/Models/ConexaoInternetSalaModel.cs
  Codigo/ModuloDeSoftware/AutomacaoSalas/Models/ViewModel/SalaViewModel.cs
  Codigo/ModuloDeSoftware/AutomacaoSalas/SalasWeb/Controllers/SalaController.cs
  Codigo/ModuloDeSoftware/AutomacaoSalas/SalasWeb/Startup.cs
  Codigo/ModuloDeSoftware/AutomacaoSalas/SalasWeb/Views/Sala/Details.cshtml
Labels: enhancement

#294 usar setas para aumentar e diminuir priorização da sala no create
  Codigo/ModuloDeSoftware/AutomacaoSalas/Business/SalaService.cs
  Codigo/ModuloDeSoftware/AutomacaoSalas/SalasWeb/Views/Sala/Create.cshtml
Labels: enhancement, correcao

#295 Filtrar corretamente os pontos de acesso.
  Codigo/ModuloDeSoftware/AutomacaoSalas/SalasWeb/Controllers/SalaController.cs
  Codigo/ModuloDeSoftware/AutomacaoSalas/SalasWeb/Views/Sala/Create.cshtml
Labels: enhancement, correcao
